# Generated by Django 4.2.7 on 2023-12-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('tearcher', 'tearcher'), ('tearcher', 'tearcher'), ('student', 'student'), ('secretary', 'secretary'), ('bursar', 'bursar'), ('dos', 'dos'), ('head', 'head')], max_length=20),
        ),
    ]
