# Generated by Django 4.2.7 on 2023-12-16 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_students_date_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
