# Generated by Django 4.2.7 on 2023-12-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_students_student_rename_teachers_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
