# Generated by Django 4.2.7 on 2023-12-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_gender_alter_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('female', 'F'), ('male', 'M')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('female', 'F'), ('male', 'M')], max_length=10),
        ),
    ]
