# Generated by Django 4.2.7 on 2023-12-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_gender_alter_teacher_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('tearcher', 'tearcher'), ('student', 'student'), ('secretary', 'secretary'), ('bursar', 'bursar'), ('dos', 'dos'), ('head', 'head')], max_length=20),
        ),
    ]
